# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getDistance <- function(flow_path_nodeIDs, stream_path_dist, total_edgelist) {
    .Call('_GeoNetParallel_getDistance', PACKAGE = 'GeoNetParallel', flow_path_nodeIDs, stream_path_dist, total_edgelist)
}

